function switchModes(e) {
    catMode = !catMode;
    localStorage.setItem("catMode", catMode);
    displayMode();
}

function displayMode() {
    document.querySelector('body').id = catMode ? "dark" : "";

    const pets = document.querySelectorAll('.pet');
    pets.forEach(pet => pet.innerText = catMode ? 'Cat' : 'Dog');

    const praises = ['Rule', 'Are Awesome', 'Are Great', 'Are the Best', 'FTW', 'Forever'];
    const random = Math.floor(Math.random() * praises.length);
    document.getElementById('praise').innerText = praises[random];

    document.getElementById('facts-link').href = catMode ? "https://catfact.ninja/" : "https://kinduff.github.io/dog-api/";

    document.getElementById('photos-link').href = catMode ? "https://thecatapi.com/" : "https://dog.ceo/dog-api/";

    let icons = document.querySelectorAll('h1 i');
    icons.forEach(icon => {
        icon.classList.add(`${catMode ? 'fa-cat' : 'fa-dog'}`);
        icon.classList.remove(`${catMode ? 'fa-dog' : 'fa-cat'}`);
    });
    let facts = "";
    let indices = [];
    if (catMode) {
        for (let i = 0; i < 4; i++) {
            indices.push(Math.floor(Math.random() * catFacts.length));
        }
        facts = indices.map(i => `<li>${catFacts[i]}</li>`).join('');
    } else {
        for (let i = 0; i < 4; i++) {
            indices.push(Math.floor(Math.random() * dogFacts.length));
        }
        facts = indices.map(i => `<li>${dogFacts[i]}</li>`).join('');
    }
    document.getElementById('fact').innerHTML = `<ul>${facts}</ul>`;

    if (catMode) {
        fetch('https://api.thecatapi.com/v1/images/search?mime_types=jpg,png')
            .then(res => res.json())
            .then(data => {
                document.getElementById("photo").style.backgroundImage =
                    `url("${data[0].url}")`;
            }).catch(error => console.log(error));
        fetch("https://catfact.ninja/facts?limit=10")
            .then(res => res.json())
            .then(data => {
                console.log(data)
                //document.getElementById("fact").innerText = JSON.parse(data);
            }).catch(error => console.log(error));
    } else {
        fetch('https://dog.ceo/api/breeds/image/random')
            .then(res => res.json())
            .then(data => {
                document.getElementById("photo").style.backgroundImage =
                    `url("${data.message}")`;
            }).catch(error => console.log(error));
    }

}

const switcher = document.getElementById('catMode');
let catMode = localStorage.getItem("catMode") === 'true';
switcher.checked = catMode;
switcher.addEventListener('click', switchModes);


const catFacts = [
    "Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.",
    "When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.",
    "The technical term for a cat's hairball is a \"bezoar.\"",
    "A group of cats is called a \"clowder.\"",
    "A cat can't climb head first down a tree because every claw on a cat's paw points the same way. To get down from a tree, a cat must back down.",
    "Cats make about 100 different sounds. Dogs make only about 10.",
    "Every year, nearly four million cats are eaten in Asia.",
    "There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.",
    "Approximately 24 cat skins can make a coat.",
    "While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.",
    "During the time of the Spanish Inquisition, Pope Innocent VIII condemned cats as evil and thousands of cats were burned. Unfortunately, the widespread killing of cats led to an explosion of the rat population, which exacerbated the effects of the Black Death.",
    "During the Middle Ages, cats were associated with withcraft, and on St. John's Day, people all over Europe would stuff them into sacks and toss the cats into bonfires. On holy days, people celebrated by tossing cats from church towers.",
    "The first cat in space was a French cat named Felicette (a.k.a. \"Astrocat\") In 1963, France blasted the cat into outer space. Electrodes implanted in her brains sent neurological signals back to Earth. She survived the trip.",
    "The group of words associated with cat (catt, cath, chat, katze) stem from the Latin catus, meaning domestic cat, as opposed to feles, or wild cat.",
    "The term \"puss\" is the root of the principal word for \"cat\" in the Romanian term pisica and the root of secondary words in Lithuanian (puz) and Low German puus. Some scholars suggest that \"puss\" could be imitative of the hissing sound used to get a cat's attention. As a slang word for the female pudenda, it could be associated with the connotation of a cat being soft, warm, and fuzzy.",
    "Approximately 40,000 people are bitten by cats in the U.S. annually.",
    "Cats are the world's most popular pets, outnumbering dogs by as many as three to one",
    "Cats are North America's most popular pets: there are 73 million cats compared to 63 million dogs. Over 30% of households in North America own a cat.",
    "According to Hebrew legend, Noah prayed to God for help protecting all the food he stored on the ark from being eaten by rats. In reply, God made the lion sneeze, and out popped a cat.",
    "A cat's hearing is better than a dog's. And a cat can hear high-frequency sounds up to two octaves higher than a human.",
    "A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance.",
    "A cat rubs against people not only to be affectionate but also to mark out its territory with scent glands around its face. The tail area and paws also carry the cat's scent.",
    "Researchers are unsure exactly how a cat purrs. Most veterinarians believe that a cat purrs by vibrating vocal folds deep in the throat. To do this, a muscle in the larynx opens and closes the air passage about 25 times per second.",
    "When a family cat died in ancient Egypt, family members would mourn by shaving off their eyebrows. They also held elaborate funerals during which they drank wine and beat their breasts. The cat was embalmed with a sculpted wooden mask and the tiny mummy was placed in the family tomb or in a pet cemetery with tiny mummies of mice.",
    "In 1888, more than 300,000 mummified cats were found an Egyptian cemetery. They were stripped of their wrappings and carted off to be used by farmers in England and the U.S. for fertilizer.",
    "Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens, of which 15 survived.",
    "Smuggling a cat out of ancient Egypt was punishable by death. Phoenician traders eventually succeeded in smuggling felines, which they sold to rich people in Athens and other important cities.",
    "The earliest ancestor of the modern cat lived about 30 million years ago. Scientists called it the Proailurus, which means \"first cat\" in Greek. The group of animals that pet cats belong to emerged around 12 million years ago.",
    "The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet (3.6 m) long (about the size of a small car) and weigh up to 700 pounds (317 kg).",
    "Cats have 300 million neurons; dogs have about 160 million",
    "A cat's brain is biologically more similar to a human brain than it is to a dog's. Both humans and cats have identical regions in their brains that are responsible for emotions.",
    "Many Egyptians worshipped the goddess Bast, who had a woman's body and a cat's head.",
    "Mohammed loved cats and reportedly his favorite cat, Muezza, was a tabby. Legend says that tabby cats have an \"M\" for Mohammed on top of their heads because Mohammad would often rest his hand on the cat's head.",
    "While many parts of Europe and North America consider the black cat a sign of bad luck, in Britain and Australia, black cats are considered lucky.",
    "The most popular pedigreed cat is the Persian cat, followed by the Main Coon cat and the Siamese cat.",
    "The smallest pedigreed cat is a Singapura, which can weigh just 4 lbs (1.8 kg), or about five large cans of cat food. The largest pedigreed cats are Maine Coon cats, which can weigh 25 lbs (11.3 kg), or nearly twice as much as an average cat weighs.",
    "Some cats have survived falls of over 65 feet (20 meters), due largely to their \"righting reflex.\" The eyes and balance organs in the inner ear tell it where it is in space so the cat can land on its feet. Even cats without a tail have this ability.",
    "Some Siamese cats appear cross-eyed because the nerves from the left side of the brain go to mostly the right eye and the nerves from the right side of the brain go mostly to the left eye. This causes some double vision, which the cat tries to correct by \"crossing\" its eyes.",
    "Researchers believe the word \"tabby\" comes from Attabiyah, a neighborhood in Baghdad, Iraq. Tabbies got their name because their striped coats resembled the famous wavy patterns in the silk produced in this city.",
    "Cats have \"nine lives\" thanks to a flexible spine and powerful leg and back muscles",
    "A cat can jump up to five times its own height in a single bound.",
    "Cats hate the water because their fur does not insulate well when it's wet. The Turkish Van, however, is one cat that likes swimming. Bred in central Asia, its coat has a unique texture that makes it water resistant.",
    "The Egyptian Mau is probably the oldest breed of cat. In fact, the breed is so ancient that its name is the Egyptian word for \"cat.\"",
    "The first commercially cloned pet was a cat named \"Little Nicky.\" He cost his owner $50,000, making him one of the most expensive cats ever.",
    "A cat usually has about 12 whiskers on each side of its face.",
    "A cat's eyesight is both better and worse than humans. It is better because cats can see in much dimmer light and they have a wider peripheral view. It's worse because they don't see color as well as humans do. Scientists believe grass appears red to cats.",
    "Spanish-Jewish folklore recounts that Adam's first wife, Lilith, became a black vampire cat, sucking the blood from sleeping babies. This may be the root of the superstition that a cat will smother a sleeping baby or suck out the child's breath.",
    "Perhaps the most famous comic cat is the Cheshire Cat in Lewis Carroll's Alice in Wonderland. With the ability to disappear, this mysterious character embodies the magic and sorcery historically associated with cats.",
    "The smallest wildcat today is the Black-footed cat. The females are less than 20 inches (50 cm) long and can weigh as little as 2.5 lbs (1.2 kg).",
    "On average, cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life.",
    "In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.",
    "The little tufts of hair in a cat's ear that help keep out dirt direct sounds into the ear, and insulate the ears are called \"ear furnishings.\"",
    "The ability of a cat to find its way home is called \"psi-traveling.\" Experts think cats either use the angle of the sunlight to find their way or that cats have magnetized cells in their brains that act as compasses.",
    "Isaac Newton invented the cat flap. Newton was experimenting in a pitch-black room. Spithead, one of his cats, kept opening the door and wrecking his experiment. The cat flap kept both Newton and Spithead happy.",
    "The world's rarest coffee, Kopi Luwak, comes from Indonesia where a wildcat known as the luwak lives. The cat eats coffee berries and the coffee beans inside pass through the stomach. The beans are harvested from the cat's dung heaps and then cleaned and roasted. Kopi Luwak sells for about $500 for a 450 g (1 lb) bag.",
    "A cat's jaw can't move sideways, so a cat can't chew large chunks of food.",
    "A cat almost never meows at another cat, mostly just humans. Cats typically will spit, purr, and hiss at other cats.",
    "Like humans, cats tend to favor one paw over another",
    "Female cats tend to be right pawed, while male cats are more often left pawed. Interestingly, while 90% of humans are right handed, the remaining 10% of lefties also tend to be male.",
    "A cat's back is extremely flexible because it has up to 53 loosely fitting vertebrae. Humans only have 34.",
    "All cats have claws, and all except the cheetah sheath them when at rest.",
    "Two members of the cat family are distinct from all others: the clouded leopard and the cheetah. The clouded leopard does not roar like other big cats, nor does it groom or rest like small cats. The cheetah is unique because it is a running cat; all others are leaping cats. They are leaping cats because they slowly stalk their prey and then leap on it.",
    "A cat lover is called an Ailurophilia (Greek: cat+lover).",
    "In Japan, cats are thought to have the power to turn into super spirits when they die. This may be because according to the Buddhist religion, the body of the cat is the temporary resting place of very spiritual people.i",
    "Most cats had short hair until about 100 years ago, when it became fashionable to own cats and experiment with breeding.",
    "One reason that kittens sleep so much is because a growth hormone is released only during sleep.",
    "Cats have about 130,000 hairs per square inch (20,155 hairs per square centimeter).",
    "The heaviest cat on record is Himmy, a Tabby from Queensland, Australia. He weighed nearly 47 pounds (21 kg). He died at the age of 10.",
    "The oldest cat on record was Crème Puff from Austin, Texas, who lived from 1967 to August 6, 2005, three days after her 38th birthday. A cat typically can live up to 20 years, which is equivalent to about 96 human years.",
    "The lightest cat on record is a blue point Himalayan called Tinker Toy, who weighed 1 pound, 6 ounces (616 g). Tinker Toy was 2.75 inches (7 cm) tall and 7.5 inches (19 cm) long.",
    "Approximately 1/3 of cat owners think their pets are able to read their minds.",
    "The tiniest cat on record is Mr. Pebbles, a 2-year-old cat that weighed 3 lbs (1.3 k) and was 6.1 inches (15.5 cm) high.",
    "A commemorative tower was built in Scotland for a cat named Towser, who caught nearly 30,000 mice in her lifetime.",
    "In the 1750s, Europeans introduced cats into the Americas to control pests.",
    "The first cat show was organized in 1871 in London. Cat shows later became a worldwide craze.",
    "The first cartoon cat was Felix the Cat in 1919. In 1940, Tom and Jerry starred in the first theatrical cartoon \"Puss Gets the Boot.\" In 1981 Andrew Lloyd Weber created the musical Cats, based on T.S. Eliot's Old Possum's Book of Practical Cats.",
    "The normal body temperature of a cat is between 100.5 ° and 102.5 °F. A cat is sick if its temperature goes below 100 ° or above 103 °F.",
    "A cat has 230 bones in its body. A human has 206. A cat has no collarbone, so it can fit through any opening the size of its head.",
    "Cats control the outer ear using 32 muscles; humans use 6",
    "Cats have 32 muscles that control the outer ear (humans have only 6). A cat can independently rotate its ears 180 degrees.",
    "A cat's nose pad is ridged with a unique pattern, just like the fingerprint of a human.",
    "If they have ample water, cats can tolerate temperatures up to 133 °F.",
    "Foods that should not be given to cats include onions, garlic, green tomatoes, raw potatoes, chocolate, grapes, and raisins. Though milk is not toxic, it can cause an upset stomach and gas. Tylenol and aspirin are extremely toxic to cats, as are many common houseplants. Feeding cats dog food or canned tuna that's for human consumption can cause malnutrition.",
    "A 2007 Gallup poll revealed that both men and women were equally likely to own a cat.",
    "A cat's heart beats nearly twice as fast as a human heart, at 110 to 140 beats a minute.",
    "In just seven years, a single pair of cats and their offspring could produce a staggering total of 420,000 kittens.",
    "Relative to its body size, the clouded leopard has the biggest canines of all animals' canines. Its dagger-like teeth can be as long as 1.8 inches (4.5 cm).",
    "Cats spend nearly 1/3 of their waking hours cleaning themselves.",
    "Grown cats have 30 teeth. Kittens have about 26 temporary teeth, which they lose when they are about 6 months old.",
    "Cat paws act as tempetature regulators, shock absorbers, hunting and grooming tools, sensors, and more",
    "Cats don't have sweat glands over their bodies like humans do. Instead, they sweat only through their paws.",
    "A cat called Dusty has the known record for the most kittens. She had more than 420 kittens in her lifetime.",
    "The largest cat breed is the Ragdoll. Male Ragdolls weigh between 12 and 20 lbs (5.4-9.0 k). Females weigh between 10 and 15 lbs (4.5-6.8 k).",
    "Cats are extremely sensitive to vibrations. Cats are said to detect earthquake tremors 10 or 15 minutes before humans can.",
    "In contrast to dogs, cats have not undergone major changes during their domestication process.",
    "A female cat is called a queen or a molly.",
    "In the 1930s, two Russian biologists discovered that color change in Siamese kittens depend on their body temperature. Siamese cats carry albino genes that work only when the body temperature is above 98° F. If these kittens are left in a very warm room, their points won't darken and they will stay a creamy white.",
    "There are up to 60 million feral cats in the United States alone.",
    "The oldest cat to give birth was Kitty who, at the age of 30, gave birth to two kittens. During her life, she gave birth to 218 kittens.",
    "The most traveled cat is Hamlet, who escaped from his carrier while on a flight. He hid for seven weeks behind a panel on the airplane. By the time he was discovered, he had traveled nearly 373,000 miles (600,000 km).",
    "Cats have supersonic hearing",
    "In Holland's embassy in Moscow, Russia, the staff noticed that the two Siamese cats kept meowing and clawing at the walls of the building. Their owners finally investigated, thinking they would find mice. Instead, they discovered microphones hidden by Russian spies. The cats heard the microphones when they turned on.",
    "The most expensive cat was an Asian Leopard cat (ALC)-Domestic Shorthair (DSH) hybrid named Zeus. Zeus, who is 90% ALC and 10% DSH, has an asking price of £100,000 ($154,000).",
    "The cat who holds the record for the longest non-fatal fall is Andy. He fell from the 16th floor of an apartment building (about 200 ft/.06 km) and survived.",
    "The richest cat is Blackie who was left £15 million by his owner, Ben Rea.",
    "The claws on the cat's back paws aren't as sharp as the claws on the front paws because the claws in the back don't retract and, consequently, become worn.",
    "A sexually-active feral tom-cat \"owns\" an area of about three square miles and \"sprays\" to mark his territory with strong smelling urine.",
    "A cat can sprint at about thirty-one miles per hour.",
    "An adult lion's roar can be heard up to five miles (eight kilometers) away.",
    "A cat will tremble or shiver when it is extreme pain.",
    "A cat's normal pulse is 140-240 beats per minute, with an average of 195.",
    "Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.",
    "Tigers are excellent swimmers and do not avoid water.",
    "The leopard is the most widespread of all big cats.",
    "While many cats enjoy milk, it will give some cats diarrhea.",
    "Female cats are polyestrous",
    "A cat will tremble or shiver when it is in extreme pain.",
    "The cat appears to be the only domestic companion animal not mentioned in the Bible.",
    "Some common houseplants poisonous to cats include: English Ivy, iris, mistletoe, philodendron, and yew.",
    "Some notable people who disliked cats:  Napoleon Bonaparte, Dwight D. Eisenhower, Hitler.",
    "Cats step with both left legs, then both right legs when they walk or run.",
    "A domestic cat can run at speeds of 30 mph.",
    "The domestic cat is the only species able to hold its tail vertically while walking. You can also learn about your cat's present state of mind by observing the posture of his tail.",
    "Cats lap liquid from the underside of their tongue, not from the top.",
    "Cats take between 20-40 breaths per minute.",
    "The Maine Coone is the only native American long haired breed.",
    "Statistics indicate that animal lovers in recent years have shown a preference for cats over dogs!",
    "It has been scientifically proven that owning cats is good for our health and can decrease the occurrence of high blood pressure and other illnesses.",
    "Cats have been domesticated for half as long as dogs have been.",
    "The largest breed of cat is the Ragdoll with males weighing in at 1 5 to 20 lbs. The heaviest domestic cat on record was a neutered male tabby named Himmy from Queensland, Australia who weighed 46 lbs. 1 5 oz.",
    "The first formal cat show was held in England in 1871; in America, in 1895.",
    "The average litter of kittens is between 2 - 6 kittens.",
    "In one stride, a cheetah can cover 23 to 26 feet (7 to 8 meters).",
    "Cats are now Britain's favourite pet: there are 7.7 million cats as opposed to 6.6 million dogs.",
    "A cat sees about 6 times better than a human at night, and needs 1/6 the amount of of light that a human does - it has a layer of extra reflecting cells which absorb light.",
    "The cat's tail is used to maintain balance.",
    "A cat's brain is more similar to a man's brain than that of a dog.",
    "According to a Gallup poll, most American pet owners obtain their cats by adopting strays.",
    "A cat's normal temperature varies around 101 degrees Fahrenheit.",
    "Cats respond better to women than to men, probably due to the fact that women's voices have a higher pitch.",
    "It may take as long as 2 weeks for a kitten to be able to hear well.  Their eyes usually open between 7 and 10 days, but sometimes it happens in as little as 2 days.",
    "A form of AIDS exists in cats.",
    "The cheetah is the world's fastest land mammal. It can run at speeds of up to 70 miles an hour (113 kilometers an hour).",
    "Tabby cats are thought to get their name from Attab, a district in Baghdad, now the capital of Iraq.",
    "When a cats rubs up against you, the cat is marking you with it's scent claiming ownership.",
    "The average lifespan of an outdoor-only cat is about 3 to 5 years while an indoor-only cat can live 16 years or much longer.",
    "The Maine Coon cat is America's only natural breed of domestic feline. It is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
    "In 1987 cats overtook dogs as the number one pet in America.",
    "A cat can jump 5 times as high as it is tall.",
    "Since cats are so good at hiding illness, even a single instance of a symptom should be taken very seriously.",
    "Retractable claws are a physical phenomenon that sets cats apart from the rest of the animal kingdom. I n the cat family, only cheetahs cannot retract their claws.",
    "A steady diet of dog food may cause blindness in your cat - it lacks taurine.",
    "When a domestic cat goes after mice, about 1 pounce in 3 results in a catch.",
    "Cats have 30 teeth (12 incisors, 10 premolars, 4 canines, and 4 molars), while dogs have 42. Kittens have baby teeth, which are replaced by permanent teeth around the age of 7 months.",
    "Many cats love having their forehead gently stroked.",
    "A cat has two vocal chords, and can make over 100 sounds.",
    "Mountain lions are strong jumpers, thanks to muscular hind legs that are longer than their front legs.",
    "Cats bury their feces to cover their trails from predators.",
    "In an average year, cat owners in the United States spend over $2 billion on cat food.",
    "The Ancient Egyptian word for cat was mau, which means \"to see\".",
    "The name \"jaguar\" comes from a Native American word meaning \"he who kills with one leap\".",
    "Cats, especially older cats, do get cancer. Many times this disease can be treated successfully.",
    "There are approximately 100 breeds of cat.",
    "Like birds, cats have a homing ability that uses its biological clock, the angle of the sun, and the Earth's magnetic field. A cat taken far from its home can return to it. But if a cat's owners move far from its home, the cat can't find them.",
    "Cat's urine glows under a black light.",
    "The chlorine in fresh tap water irritates sensitive parts of the cat's nose. Let tap water sit for 24 hours before giving it to a cat.",
    "If your cat snores, or rolls over on his back to expose his belly, it means he trusts you.",
    "Cats lived with soldiers in trenches, where they killed mice during World War I.",
    "About 37% of American homes today have at least 1 cat.",
    "The female cat reaches sexual maturity within 6 to 10 months; most veterinarians suggest spaying the female at 5 months, before her first heat period. The male cat usually reaches sexual maturity between 9 and 12 months.",
    "Kittens remain with their mother till the age of 9 weeks.",
    "Cats can predict earthquakes. We humans are not 100% sure how they do it. There are several different theories.",
    "The way you treat kittens in the early stages of it's life will render it's personality traits later in life.",
    "Cats' eyes shine in the dark because of the tapetum, a reflective layer in the eye, which acts like a mirror.",
    "A cat's jaw has only up and down motion; it does not have any lateral, side to side motion, like dogs and humans.",
    "A tomcat (male cat) can begin mating when he is between 7 and 10 months old.",
    "Today there are about 100 distinct breeds of the domestic cat.",
    "Julius Ceasar, Henri II, Charles XI, and Napoleon were all afraid of cats.",
    "A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds, slightly less for female housecats.",
    "Cats have the largest eyes of any mammal.",
    "Cats can judge within 3 inches the precise location of a sound being made 1 yard away.",
    "Lions are the only cats that live in groups, called prides. Every female within the pride is usually related.",
    "Cats should not be fed tuna exclusively, as it lacks taurine, an essential nutrient required for good feline health.  Make sure you have the proper Pet supplies to keep your cat happy and healthy.",
    "Most cats adore sardines.",
    "Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.",
    "The ancestor of all domestic cats is the African Wild Cat which still exists today.",
    "Cats have 32 muscles that control the outer ear (compared to human's 6 muscles each). A cat can rotate its ears independently 180 degrees, and can turn in the direction of sound 10 times faster than those of the best watchdog.",
    "The cat's front paw has 5 toes, but the back paws have 4. Some cats are born with as many as 7 front toes and extra back toes (polydactl).",
    "Long, muscular hind legs enable snow leopards to leap seven times their own body length in a single bound.",
    "Cats purr at the same frequency as an idling diesel engine, about 26 cycles per second.",
    "A cat has more bones than a human; humans have 206, but the cat has 230 (some cites list 245 bones, and state that bones may fuse together as the cat ages).",
    "Many cats cannot properly digest cow's milk. Milk and milk products give them diarrhea.",
    "A cat's normal pulse is 140-240 beats per minute, with an average of 195.",
    "Kittens who are taken along on short, trouble-free car trips to town tend to make good passengers when they get older. They get used to the sounds and motions of traveling and make less connection between the car and the visits to the vet.",
    "All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.",
    "Neutering a male cat will, in almost all cases, stop him from spraying (territorial marking), fighting with other males (at least over females), as well as lengthen his life and improve its quality.",
    "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
    "Not every cat gets \\high\\\" from catnip. Whether or not a cat responds to it depends upon a recessive gene: no gene\"",
    "A cat can spend five or more hours a day grooming himself.",
    "British cat owners spend roughly 550 million pounds yearly on cat food.",
    "Purring does not always indicate that a cat is happy. Cats will also purr loudly when they are distressed or in pain.",
    "It is estimated that cats can make over 60 different sounds.",
    "Heat occurs several times a year and can last anywhere from 3 to 15 days.",
    "Cats' hearing is much more sensitive than humans and dogs.",
    "Cats must have fat in their diet because they can't produce it on their own.",
    "Blue-eyed, pure white cats are frequently deaf.",
    "A female cat will be pregnant for approximately 9 weeks or between 62 and 65 days from conception to delivery.",
    "In ancient Egypt, when a family cat died, all family members would shave their eyebrows as a sign of mourning.",
    "The Amur leopard is one of the most endangered animals in the world.",
    "Cats and kittens should be acquired in pairs whenever possible as cat families interact best in pairs.",
    "On average, a cat will sleep for 16 hours a day.",
    "Cats sleep 16 to 18 hours per day. When cats are asleep, they are still alert to incoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.",
    "A tiger's stripes are like fingerprints",
    "The life expectancy of cats has nearly doubled over the last fifty years.",
    "A cat's field of vision is about 200 degrees.",
    "Ancient Egyptian family members shaved their eyebrows in mourning when the family cat died.",
    "A healthy cat has a temperature between 38 and 39 degrees Celcius.",
    "Unlike other cats, lions have a tuft of hair at the end of their tails.",
    "Both humans and cats have identical regions in the brain responsible for emotion.",
    "Jaguars are the only big cats that don't roar.",
    "Of all the species of cats, the domestic cat is the only species able to hold its tail vertically while walking. All species of wild cats hold their tail horizontally or tucked between their legs while walking.",
    "Edward Lear, author of \\The Owl and the Pussycat\\\"\", is said to have had his new house in San Remo built to exactly the same specification as his previous residence, so that his much-loved tabby, Foss, would immediately feel at home.\"\"\"",
    "Cats can be right-pawed or left-pawed.",
    "Cats do not think that they are little people. They think that we are big cats. This influences their behavior in many ways.",
    "Cats walk on their toes.",
    "The first official cat show in the UK was organised at Crystal Palace in 1871.",
    "The first cat show was in 1871 at the Crystal Palace in London.",
    "In just 7 years, one un-spayed female cat and one un-neutered male cat and their offspring can result in 420,000 kittens.",
    "When your cats rubs up against you, she is actually marking you as 'hers' with her scent. If your cat pushes his face against your head, it is a sign of acceptance and affection.",
    "Tests done by the Behavioral Department of the Musuem of Natural History conclude that while a dog's memory lasts about 5 minutes, a cat's recall can last as long as 16 hours.",
    "The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer. Some cats have been documented to have a longevity of 34 years.",
    "A happy cat holds her tail high and steady.",
    "The cat's clavicle, or collarbone, does not connect with other bones but is buried in the muscles of the shoulder region. This lack of a functioning collarbone allows them to fit through any opening the size of their head.",
    "Cats come back to full alertness from the sleep state faster than any other creature.",
    "When a cat drinks, its tongue - which has tiny barbs on it - scoops the liquid up backwards.",
    "Cats see six times better in the dark and at night than humans.",
    "Purring does not always indicate that a cat is happy and healthy - some cats will purr loudly when they are terrified or in pain.",
    "People who are allergic to cats are actually allergic to cat saliva or to cat dander. If the resident cat is bathed regularly the allergic people tolerate it better.",
    "If a cat is frightened, the hair stands up fairly evenly all over the body; when the cat is threatened or is ready to attack, the hair stands up only in a narrow band along the spine and tail.",
    "Blue-eyed, white cats are often prone to deafness.",
    "In relation to their body size, cats have the largest eyes of any mammal.",
    "An adult lion's roar can be heard up to five miles (eight kilometers) away.",
    "Female felines are \\superfecund",
    "At 4 weeks, it is important to play with kittens so that they do not develope a fear of people.",
    "A cat's whiskers are thought to be a kind of radar, which helps a cat gauge the space it intends to walk through.",
    "Abraham Lincoln loved cats. He had four of them while he lived in the White House.",
    "In 1987 cats overtook dogs as the number one pet in America.",
    "A cat uses its whiskers for measuring distances.  The whiskers of a cat are capable of registering very small changes in air pressure.",
    "A cat has more bones than a human; humans have 206, and the cat - 230.",
    "Cats dislike citrus scent.",
    "It has been scientifically proven that stroking a cat can lower one's blood pressure.",
    "Cats respond most readily to names that end in an \"ee\" sound.",
    "Neutering a cat extends its life span by two or three years.",
    "Cat families usually play best in even numbers. Cats and kittens should be acquired in pairs whenever possible.",
    "The Pilgrims were the first to introduce cats to North America.",
    "After humans, mountain lions have the largest range of any mammal in the Western Hemisphere.",
    "Among many other diseases, cats can suffer from anorexia, senility, feline AIDS and acne.",
    "Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do this more often, especially when they are excited.",
    "Miacis, the primitive ancestor of cats, was a small, tree-living creature of the late Eocene period, some 45 to 50 million years ago.",
    "A cat's hearing is much more sensitive than humans and dogs.",
    "A cat will tremble or shiver when it is extreme pain.",
    "In 1987, cats overtook dogs as the number one pet in America (about 50 million cats resided in 24 million homes in 1986). About 37% of American homes today have at least one cat.",
    "Contrary to popular belief, the cat is a social animal. A pet cat will respond and answer to speech , and seems to enjoy human companionship.",
    "The Maine Coon is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
    "A cat has approximately 60 to 80 million olfactory cells (a human has between 5 and 20 million).",
    "Cats can be taught to walk on a leash, but a lot of time and patience is required to teach them. The younger the cat is, the easier it will be for them to learn.",
    "A cats field of vision is about 185 degrees.",
    "You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.",
    "The strongest climber among the big cats, a leopard can carry prey twice its weight up a tree.",
    "The first true cats came into existence about 12 million years ago and were the Proailurus.",
    "There is a species of cat smaller than the average housecat. It is native to Africa and it is the Black-footed cat (Felis nigripes). Its top weight is 5.5 pounds.",
    "Phoenician cargo ships are thought to have brought the first domesticated cats to Europe in about 900 BC.",
    "Cat families usually play best in even numbers. Cats and kittens should be aquired in pairs whenever possible.",
    "Cheetahs do not roar, as the other big cats do. Instead, they purr.",
    "Ailurophile is the word cat lovers are officially called.",
    "The cat has 500 skeletal muscles (humans have 650).",
    "Cats are subject to gum disease and to dental caries. They should have their teeth cleaned by the vet or the cat dentist once a year.",
    "Florence Nightingale owned more than 60 cats in her lifetime.",
    "Cat bites are more likely to become infected than dog bites.",
    "Tylenol and chocolate are both poisionous to cats.",
    "A cat named Dusty, aged 1 7, living in Bonham, Texas, USA, gave birth to her 420th kitten on June 23, 1952.",
    "In ancient Egypt, mummies were made of cats, and embalmed mice were placed with them in their tombs. In one ancient city, over 300,000 cat mummies were found.",
    "Fossil records from two million years ago show evidence of jaguars.",
    "In multi-cat households, cats of the opposite sex usually get along better.",
    "Normal body temperature for a cat is 102 degrees F.",
    "A cat cannot see directly under its nose.",
    "Baking chocolate is the most dangerous chocolate to your cat.",
    "Unlike humans, cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.",
    "Cats, just like people, are subject to asthma. Dust, smoke, and other forms of air pullution in your cat's environment can be troublesome sources of irritation.",
    "Cats' hearing stops at 65 khz (kilohertz); humans' hearing stops at 20 khz.",
    "All cats need taurine in their diet to avoid blindness. Cats must also have fat in their diet as they are unable to produce it on their own.",
    "Cats eat grass to aid their digestion and to help them get rid of any fur in their stomachs.",
    "The average cat food meal is the equivalent to about five mice.",
    "In Siam, the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.",
    "The cat's footpads absorb the shocks of the landing when the cat jumps.",
    "Siamese kittens are born white because of the heat inside the mother's uterus before birth. This heat keeps the kittens' hair from darkening on the points.",
    "There are approximately 60,000 hairs per square inch on the back of a cat and about 120,000 per square inch on its underside.",
    "Cats have 30 vertebrae (humans have 33 vertebrae during early development; 26 after the sacral and coccygeal regions fuse)",
    "A cat has more bones than a human being; humans have 206 and the cat has 230 bones.",
    "The silks created by weavers in Baghdad were inspired by the beautiful and varied colors and markings of cat coats. These fabrics were called 'tabby' by European traders.",
    "Cats often overract to unexpected stimuli because of their extremely sensitive nervous system.",
    "Cats can jump up to 7 times their tail length.",
    "A queen (female cat) can begin mating when she is between 5 and 9 months old.",
    "Milk can give some cats diarrhea.",
    "The cat appears to be the only domestic companion animal not mentioned in the Bible.",
    "The life expectancy of cats has nearly doubled since 1930 - from 8 to 16 years.",
    "A cat's appetite is the barometer of its health. Any cat that does not eat or drink for more than two days should be taken to a vet.",
    "Unlike humans, cats cannot detect sweetness which likely explains why they are not drawn to it at all.",
    "Ginger tabby cats can have freckles around their mouths and on their eyelids!",
    "A cat has the power to sometimes heal themselves by purring. A domestic cat's purr has a frequency of between 25 and 150 Hertz, which happens to be the frequency at which muscles and bones best grow and repair themselves. ",
    "Cats only use their meows to talk to humans, not each other. The only time they meow to communicate with other felines is when they are kittens to signal to their mother.",
    "Despite imagery of cats happily drinking milk from saucers, studies indicate that cats are actually lactose intolerant and should avoid it entirely.",
    "The longest living cat on record according to the Guinness Book belongs to the late Creme Puff of Austin, Texas who lived to the ripe old age of 38 years and 3 days!",
    "The Cat Fanciers Association (CFA) recognizes 44 breeds of cats.",
    "A cat's cerebral cortex contains about twice as many neurons as that of dogs. Cats have 300 million neurons, whereas dogs have about 160 million. See, cats rule, dogs drool!",
    "Polydactyl cats (a cat with 1-2 extra toes on their paws) have this as a result of a genetic mutation. These cats are also referred to as 'Hemingway cats' because writer Ernest Hemingway reportedly owned dozens of them at his home in Key West, Florida.",
    "Sir Isaac Newton is credited with creating the concept for the pet door that many cats use today to travel outdoors.",
    "The average cat can jump 8 feet in a single bound, nearly six times its body length!",
    "A cat's smell is their strongest sense, and they rely on this leading sense to identify people and objects; a feline's sense of smell is 14x better than a human's.",
    "Cats only sweat through their paws and nowhere else on their body",
    " A cat only has the ability to move their jaw up and down, not side to side like a human can.",
    "A group of cats is called a clowder.",
    "A female cat can be referred to as a molly or a queen, and a male cat is often labeled as a tom.",
    "A cat has the ability to rotate their ears 180 degrees,with the help of 32 muscles that they use to control them.",
    "70% of your cat's life is spent asleep.",
    "A cat's nose is as unique as a human's fingerprint.",
    "Cats have 3 eyelids.",
    "Your cat's heart beats at a rate almost double that of yours, from 110-140 beats per minute.",
    "In Ancient Egypt, when a person's house cat passed away, the owner would shave their eyebrows to reflect their grief.",
    "Owning a cat is actually proven to be beneficial for your health.",
    "Cats prefer to remain non-confrontational. They will not fight to show dominance, but rather to stake their territory. Cats will actually go to extremes to avoid one another in order to prevent a possible confrontation.",
    "Unlike humans, cats are usually lefties. Studies indicate that their left paw is typically their dominant paw."
];

const dogFacts = [
    "All dogs can be traced back 40 million years ago to a weasel-like animal called the Miacis which dwelled in trees and dens. The Miacis later evolved into the Tomarctus, a direct forbear of the genus Canis, which includes the wolf and jackal as well as the dog.",
    "Ancient Egyptians revered their dogs. When a pet dog would die, the owners shaved off their eyebrows, smeared mud in their hair, and mourned aloud for days.",
    "Small quantities of grapes and raisins can cause renal failure in dogs. Chocolate, macadamia nuts, cooked onions, or anything with caffeine can also be harmful.",
    "Apple and pear seeds contain arsenic, which may be deadly to dogs.",
    "Rock star Ozzy Osborne saved his wife Sharon's Pomeranian from a coyote by tackling and wresting the coyote until it released the dog.",
    "Dogs have sweat glands in between their paws.",
    "In 2003, Dr. Roger Mugford invented the \"wagometer,\" a device that claims to interpret a dog's exact mood by measuring the wag of its tail.",
    "Dogs have three eyelids. The third lid, called a nictitating membrane or \"haw,\" keeps the eye lubricated and protected.",
    "A dog's shoulder blades are unattached to the rest of the skeleton to allow greater flexibility for running.",
    "Puppies are sometimes rejected by their mother if they are born by cesarean and cleaned up before being given back to her.",
    "The phrase \"raining cats and dogs\" originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.",
    "During the Middle Ages, Great Danes and Mastiffs were sometimes suited with armor and spiked collars to enter a battle or to defend supply caravans.",
    "Pekingese and Japanese Chins were so important in the ancient Far East that they had their own servants and were carried around trade routes as gifts for kings and emperors. Pekingese were even worshipped in the temples of China for centuries.",
    "The shape of a dog's face suggests how long it will live. Dogs with sharp, pointed faces that look more like wolves typically live longer. Dogs with very flat faces, such as bulldogs, often have shorter lives.",
    "After the fall of Rome, human survival often became more important than breeding and training dogs. Legends of werewolves emerged during this time as abandoned dogs traveling in packs commonly roamed streets and terrified villagers.",
    "During the Middle Ages, mixed breeds of peasants' dogs were required to wear blocks around their necks to keep them from breeding with noble hunting dogs. Purebred dogs were very expensive and hunting became the province of the rich.",
    "The most dogs ever owned by one person were 5,000 Mastiffs owned by Kublai Khan.",
    "The American Kennel Club, the most influential dog club in the United States, was founded in 1884.",
    "The most popular male dog names are Max and Jake. The most popular female dog names are Maggie and Molly.",
    "Scholars have argued over the metaphysical interpretation of Dorothy's pooch, Toto, in the Wizard of Oz. One theory postulates that Toto represents Anubis, the dog-headed Egyptian god of death, because Toto consistently keeps Dorothy from safely returning home.",
    "Weird dog laws include allowing police offers in Palding, Ohio, to bite a dog to quiet it. In Ventura County, California, cats and dogs are not allowed to have sex without a permit.",
    "The first dog chapel was established in 2001. It was built in St. Johnsbury, Vermont, by Stephan Huneck, a children's book author whose five dogs helped him recuperate from a serious illness.",
    "Those born under the sign of the dog in Chinese astrology are considered to be loyal and discreet, though slightly temperamental.",
    "In Iran, it is against the law to own a dog as a pet. However, if an owner can prove the dog is a guard or hunting dog, this restriction doesn't apply. Muslim reticence concerning dogs is perhaps due to the fact that rabies has always been endemic in the Middle East.",
    "The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.",
    "The ancient Mbaya Indians of the Gran Chaco in South America believed that humans originally lived underground until dogs dug them up.",
    "Plato once said that \"a dog has the soul of a philosopher.\"",
    "French poodles did not originate in France but in Germany (\"poodle\" comes from the German pudel or pudelhund, meaning \"splashing dog\"). Some scholars speculate the poodle's puffs of hair evolved when hunters shaved the poodle for more efficient swimming, while leaving the pom-poms around the major joints to keep them warm.",
    "The name of the dog on the Cracker Jacks box is Bingo. The Taco Bell Chihuahua is a rescued dog named Gidget.",
    "The first dogs were self-domesticated wolves which, at least 12,000 years ago, became attracted to the first sites of permanent human habitation.",
    "Dachshunds were bred to fight badgers in their dens.",
    "Laika, a Russian stray, was the first living mammal to orbit the Earth, in the Soviet Sputnik spacecraft in 1957. Though she died in space, her daughter Pushnika had four puppies with President John F. Kennedy's terrier, Charlie.",
    "Dalmatians are completely white at birth.",
    "The term \"dog days of summer\" was coined by the ancient Greeks and Romans to describe the hottest days of summer that coincided with the rising of the Dog Star, Sirius.",
    "Alexander the Great is said to have founded and named a city Peritas, in memory of his dog.",
    "In ancient Greece, kennels of dogs were kept at the sanctuary of Asclepius at Epidaurus. Dogs were frequently sacrificed there because they were plentiful, inexpensive, and easy to control. During the July 25 celebration of the kunophontis (\"the massacre of dogs\"), dog sacrifices were performed to appease the ancestors of Apollo's son, Linos, who was devoured by dogs.",
    "Dog trainers in ancient China were held in high esteem. A great deal of dog domestication also took place in China, especially dwarfing and miniaturization.",
    "The ancient religion Zoroastrianism includes in its religious text titled the Zend Avesta a section devoted to the care and breeding of dogs.",
    "The earliest European images of dogs are found in cave paintings dating back 12,000 years ago in Spain.",
    "The dog was frequently depicted in Greek art, including Cerberus, the three-headed hound guarding the entrance to the underworld, and the hunting dogs which accompanied the virgin goddess of the chase, Diana.",
    "During the Renaissance, detailed portraits of the dog as a symbol of fidelity and loyalty appeared in mythological, allegorical, and religious art throughout Europe, including works by Leonardo da Vinci, Diego Velázquez, Jan van Eyck, and Albrecht Durer.",
    "A puppy is born blind, deaf, and toothless.",
    "The Basenji is the world's only barkless dog.",
    "A dog most likely interprets a smiling person as baring their teeth, which is an act of aggression.",
    "The origin of amputating a dog's tail may go back to the Roman writer Lucius Columella's (A.D. 4-70) assertion that tail docking prevented rabies.",
    "One of Shakespeare's most mischievous characters is Crab, the dog belonging to Launce in the Two Gentlemen of Verona. The word \"watchdog\" is first found in The Tempest.",
    "President Franklin Roosevelt created a minor international incident when he claimed he sent a destroyer to the Aleutian Islands just to pick up his Scottish Terrier, Fala, who had been left behind.",
    "Within hours of the September 11, 2001, attack on the World Trade Center, specially trained dogs were on the scene, including German Shepherds, Labs, and even a few little Dachshunds.",
    "It costs approximately $10,000 to train a federally certified search and rescue dog.",
    "The smallest dog on record was a matchbox-size Yorkshire Terrier. It was 2.5\" tall at the shoulder, 3.5\" from nose tip to tail, and weighed only 4 ounces.",
    "Hollywood's first and arguably best canine superstar was Rin Tin Tin, a five-day-old German Shepherd found wounded in battle in WWI France and adopted by an American soldier, Lee Duncan. He would sign his own contracts with his paw print.",
    "At the end of WWI, the German government trained the first guide dogs for war-blinded soldiers.",
    "A dog can locate the source of a sound in 1/600 of a second and can hear sounds four times farther away than a human can.",
    "Touch is the first sense the dog develops. The entire body, including the paws, is covered with touch-sensitive nerve endings.",
    "Eighteen muscles or more can move a dog's ear.",
    "The names of 77 ancient Egyptian dogs have been recorded. The names refer to color and character, such as Blackie, Ebony, Good Herdsman, Reliable, and Brave One.",
    "In Egypt, a person bitten by a rabid dog was encouraged to eat the roasted liver of a dog infected with rabies to avoid contracting the disease. The tooth of a dog infected with rabies would also be put in a band tied to the arm of the person bitten. The menstrual blood of a female dog was used for hair removal, while dog genitals were used for preventing the whitening of hair.",
    "In early Christian tradition, Saint Christopher, the patron saint of travelers, is sometimes depicted with a dog's head.",
    "The oldest known dog bones were found in Asia and date as far back as 10,000 B.C. The first identifiable dog breed appeared about 9000 B.C. and was probably a type of Greyhound dog used for hunting.",
    "There are an estimated 400 million dogs in the world.",
    "The U.S. has the highest dog population in the world. France has the second highest.",
    "Dog nose prints are as unique as human finger prints and can be used to identify them.",
    "Bloodhound dogs have a keen sense of smell and have been used since the Middle Ages to track criminals.",
    "It is much easier for dogs to learn spoken commands if they are given in conjunction with hand signals or gestures.",
    "Dogs in a pack are more likely to chase and hunt than a single dog on its own. Two dogs are enough to form a pack.",
    "Dogs can see in color, though they most likely see colors similar to a color-blind human. They can see better when the light is low.",
    "Petting dogs is proven to lower blood pressure of dog owners.",
    "Dogs have lived with humans for over 14,000 years. Cats have lived with people for only 7,000 years.",
    "Zorba, an English mastiff, is the biggest dog ever recorded. He weighed 343 pounds and measured 8' 3\" from his nose to his tail.",
    "The average dog can run about 19 mph. Greyhounds are the fastest dogs on Earth and can run at speeds of 45 mph.",
    "One female dog and her female children could produce 4,372 puppies in seven years.",
    "The most popular dog breed in Canada, U.S., and Great Britain is the Labrador retriever.",
    "Greyhounds appear to be the most ancient dog breed. \"Greyhound\" comes from a mistake in translating the early German name Greishund, which means \"old (or ancient) dog,\" not from the color gray.",
    "The oldest dog on record was an Australian cattle dog named Bluey who lived 29 years and 5 months. In human years, that is more than 160 years old.",
    "Most experts believe humans domesticated dogs before donkeys, horses, sheep, goats, cattle, cats, or chickens.",
    "A person standing still 300 yards away is almost invisible to a dog. But a dog can easily identify its owner standing a mile away if the owner is waving his arms.",
    "Dogs with big, square heads and large ears (like the Saint Bernard) are the best at hearing subsonic sounds.",
    "Dogs can smell about 1,000 times better than humans. While humans have 5 million smell-detecting cells, dogs have more than 220 million. The part of the brain that interprets smell is also four times larger in dogs than in humans.",
    "Some dogs can smell dead bodies under water, where termites are hiding, and natural gas buried under 40 feet of dirt. They can even detect cancer that is too small to be detected by a doctor and can find lung cancer by sniffing a person's breath.",
    "Dogs have a wet nose to collect more of the tiny droplets of smelling chemicals in the air.",
    "Dogs like sweets a lot more than cats do. While cats have around only 473 taste buds, dogs have about 1,700 taste buds. Humans have approximately 9,000.",
    "Different smells in the a dog's urine can tell other dogs whether the dog leaving the message is female or male, old or young, sick or healthy, happy or angry.",
    "Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.",
    "In Croatia, scientists discovered that lampposts were falling down because a chemical in the urine of male dogs was rotting the metal.",
    "Dogs are about as smart as a two- or three-year-old child. This means they can understand about 150-200 words, including signals and hand movements with the same meaning as words.",
    "Countess Karlotta Libenstein of Germany left approximately $106 million to her Alsatin, Gunther III, when she died in 1992.",
    "A lost Dachshund was found swallowed whole in the stomach of a giant catfish in Berlin on July 2003.",
    "In Australia, a man who was arrested for drug possession argued his civil rights were violated when the drug-sniffing dog nuzzled his crotch. While the judge dismissed the charges, they were later reinstated when a prosecutor pointed out that in the animal kingdom, crotch nuzzling was a friendly gesture.",
    "The Beagle came into prominence in the 1300s and 1400s during the days of King Henry VII of England. Elizabeth I was fond of Pocket Beagles, which were only 9\" high.",
    "The best dog to reportedly attract a date is the Golden Retriever. The worst is the Pit Bull.",
    "The Akita is one of the most challenging dogs to own. Some insurance companies have even characterized it as the #1 \"bad dog\" and may even raise an Akita owner's homeowner insurance costs.",
    "The Beagle and Collie are the nosiest dogs, while the Akbash Dog and the Basenji are the quietest.",
    "One survey reports that 33% of dog owners admit they talk to their dogs on the phone or leave messages on answering machines while they are away.",
    "Thirty percent of all Dalmatians are deaf in one or both ears. Because bulldogs have extremely short muzzles, many spend their lives fighting suffocation. Because Chihuahuas have such small skulls, the flow of spinal fluid can be restricted, causing hydrocephalus, a swelling of the brain.",
    "The grief suffered after a pet dog dies can be the same as that experienced after the death of a person.",
    "There are almost 5 million dog bites per year; children are the main victims. Dog bites cause losses of over $1 billion a year.",
    "A person should never kick a dog facing him or her. Some dogs can bite 10 times before a human can respond.",
    "The most intelligent dogs are reportedly the Border Collie and the Poodle, while the least intelligent dogs are the Afghan Hound and the Basenji.",
    "One kind of Pekingese is referred to as a \"sleeve\" because it was bred to fit into a Chinese empress' sleeves, which was how it was often carried around.",
    "Is it a duck... or a dog? The Newfoundland breed has a water resistant coat and webbed feet. This dog was originally bred to help haul nets for fishermen and rescuing people at risk of drowning.",
    "It pays to be a lap dog. Three dogs (from First Class cabins!) survived the sinking of the Titanic – two Pomeranians and one Pekingese.",
    "A Beatles hit. It's rumored that, at the end of the Beatles song, \"A Day in the Life,\" Paul McCartney recorded an ultrasonic whistle, audible only to dogs, just for his Shetland sheepdog.",
    "Wow, check out those choppers! Puppies have 28 teeth and normal adult dogs have 42.",
    "Chase that tail! Dogs chase their tails for a variety of reasons: curiosity, exercise, anxiety, predatory instinct or, they might have fleas! If your dog is chasing his tail excessively, talk with your vet.",
    "Seeing spots? Or not...  Dalmatian puppies are pure white when they are born and develop their spots as they grow older.",
    "Dogs do dream! Dogs and humans have the same type of slow wave sleep (SWS) and rapid eye movement (REM) and during this REM stage dogs can dream. The twitching and paw movements that occur during their sleep are signs that your pet is dreaming",
    "No night vision goggles needed! Dogs' eyes contain a special membrane, called the tapetum lucidum, which allows them to see in the dark.",
    "Pitter patter. A large breed dog's resting heart beats between 60 and 100 times per minute, and a small dog breed's heart beats between 100-140. Comparatively, a resting human heart beats 60-100 times per minute.",
    "If your dog's acting funny, get out the umbrella! According to a Petside.com/Associated Press poll,72% of dog owners believe their dog can detect when stormy weather is on the way.",
    "It's not a fever... A dog's normal temperature is between 101 and 102.5 degrees Fahrenheit. How much do you know about dog health? Take our Doggy First Aid Quiz!",
    "Is something wet? Unlike humans who sweat everywhere, dogs only sweat through the pads of their feet.",
    "Americans love dogs! 44% of U.S. households have a dog, which equates to 55.3 million homes",
    "Move over Rover! 45% of dogs sleep in their owner's bed (we're pretty sure a large percentage also hog the blankets!)",
    "Why are dogs' noses so wet? Dogs' noses secrete a thin layer of mucous that helps them absorb scent. They then lick their noses to sample the scent through their mouth.",
    "Yummy! Dogs have about 1,700 taste buds. Humans have approximately 9,000 and cats have around 473.",
    "Watch that plate of cookies! A Dog's sense of smell is 10,000 – 100,000 times more acute as that of humans.",
    "It's not so black and white. It's a myth that dogs only see in black and white. In fact, it's believed that dogs see primarily in blue, greenish-yellow, yellow and various shades of gray.",
    "Did you hear that? Sound frequency is measured in Hertz (Hz). The higher the Hertz, the higher-pitched the sound. Dogs hear best at 8,000 Hz, while humans hear best at around 2,000 Hz.",
    "Express yourself. Dogs' ears are extremely expressive. It's no wonder! There are more than a dozen separate muscles that control a dog's ear movements.",
    "Growing up. While the Chow Chow dogs are well known for their distinctive blue-black tongues, they're actually born with pink tongues. They turn blue-black at 8-10 weeks of age.",
    "Why do they do that? When dogs kick after going to the bathroom, they are using the scent glands on their paws to further mark their territory.",
    "No, it's not just to make themselves look adorable. Dogs curl up in a ball when they sleep due to an age-old instinct to keep themselves warm and protect their abdomen and vital organs from predators.",
    "Dogs are capable of understanding up to 250 words and gestures, can count up to five and can perform simple mathematical calculations. The average dog is as intelligent as a two-year-old child.",
    "Some stray Russian dogs have figured out how to use the subway system in order to travel to more populated areas in search of food.",
    "Dogs don't enjoy being hugged as much as humans and other primates. Canines interpret putting a limb over another animal as a sign of dominance.",
    "Two stray dogs in Afghanistan saved 50 American soliders. A Facebook group raised $21,000 to bring the dogs back to the US and reunite them with the soldiers.",
    "This pup, Nesbit, earned over one million Delta airline miles in his life and had his own frequent flier card.",
    "One of Michael Vick's former fighting dogs, Leo, went on to be a therapy dog who comforted dying children.",
    "Service dogs are trained to know when they are on duty. When their harness is on, they know it's business time. When you take it off, the pups immediately become playful and energetic.",
    "Tiger Woods stuttered as a child and used to talk to his dog until he fell asleep in an effort to get rid of it.",
    "Seeing eye dogs pee and poo on command so that their owners can clean up after them. (The command is usually \"Get busy!\" and pups will pace back and forth until they do their business.) Male dogs are also trained to do their business without lifting their leg.",
    "In ancient China, an emperor's last line of defense was a small Pekingese dog literally hidden up his sleeve.",
    "When Lord Byron was informed that his dog was not allowed to come with him to Cambridge Trinity College, he retaliated by bringing a bear instead.",
    "In 1860's San Francisco, two stray dogs who were best friends became local celebrities. Their exploits were celebrated in local papers and they were granted immunity from the city's dog catchers.",
    "There is a dog-shaped building in New Zealand.",
    "One dog, Naki'o, lost all of his legs to frostbite in Colorado, but now has four prosthetic legs and can run around like normal.",
    "The wetness of a dog's nose is essential for determining what direction a smell is coming from.",
    "Hyenas aren't actually dogs. They are more closely related to cats.",
    "Spiked dog collars were invented in ancient Greece and were originally designed to protect dogs throats from wolf attacks.",
    "Baks the blind boxer has a seeing eye goose named Buttons. Buttons the four-year-old goose leads her pup around everywhere either by hanging onto him with her neck, or by honking to tell him which way to go.",
    "'Frito Feet' is the name of the phenomenon in which the bacteria on a dog's paws cause them to smell like corn chips. Because a pup's feet are in constant contact with the ground, they pick up tons of microorganisms in their paws. When dogs cool off by sweating through the pads of their feet, the combo of moisture and bacteria releaces a nutty, popcorn-like aroma. Basically it's dog B.O.",
    "It is a myth that dogs are color blind. They can actually see in color, just not as vividly as humans. It is akin to our vision at dusk.",
    "Dogs DO have better low-light vision than humans because of a special light-reflecting layer behind their retinas.",
    "A German Shepherd guide dog led her blind companion the entire 2,100 mile Appalachian Trail.",
    "If never spayed or neutered, a female dog, her mate, and their puppies could produce over 66,000 dogs in 6 years!",
    "Dogs' only sweat glands are between their paw pads.",
    "Like human babies, Chihuahuas are born with a soft spot in their skull which closes with age.",
    "The breed Lundehune has 6 toes and can close its ears.",
    "Teddy Roosevelt's dog, Pete, ripped a French ambassador's pants off at the White House.",
    "President Lyndon Johnson had two beagles named Him and Her.",
    "Franklin Roosevelt spent $15,000 for a destroyer to pick up his Scottie in the Aleutian Islands.",
    "In Roman times, mastiffs donned light armor and were sent after mounted knights.",
    "The Russians trained dogs during WWII to run suicide missions with mines strapped to their backs.",
    "A dog's mouth exerts 150-200 pounds of pressure per square inch with some dogs exerting up to 450 pounds per square inch.",
    "A one year old dog is as physically mature as a 15 year old human.",
    "The U.S. has the highest dog population in the world.",
    "France has the 2nd highest dog population.",
    "The average city dog lives 3 years longer than a country dog.",
    "Eighty-seven percent of dog owners say their dog curls up beside them or at their feet while they watch T.V.",
    "Dogs can be trained to detect epileptic seizures in humans.",
    "Fifteen people die in the U.S. every year from dog bites.",
    "In 2002 alone, more people in the U.S. were killed by dogs than by sharks in the past 100 years.",
    "Gidget is the name of the Taco Bell dog.",
    "Newfoundlands are great swimmers because of their webbed feet.",
    "Basset Hounds cannot swim.",
    "Greyhounds are the fastest dogs on earth, with speeds of up to 45 miles per hour.",
    "Bingo is the name of the dog on the side of the Cracker Jack box.",
    "The bible mentions dogs 14 times.",
    "Three dogs survived the sinking of the Titanic: a Newfoundland, a Pomeranian, and a Pekingese.",
    "The Labrador Retriever is the #1 favorite breed in the U.S., Canada, and the U.K.",
    "Obesity is the #1 health problem among dogs.",
    "An estimated 1,000,000 dogs in the U.S. have been named as the primary beneficiaries in their owner's will.",
    "An American Animal Hospital Association poll found that 33% of dog owners admit to talking to their dogs on the phone and leaving answering machine messages for them while away.",
    "Dogs' nose prints are as unique as a human's finger prints, and can be used to accurately identify them.",
    "Seventy percent of people sign their pet's name on greeting and holiday cards.",
    "Fifty-eight percent of people put pets in family and holiday portraits.",
    "There are only 350 Cisky Terriers in the world, possibly making it the rarest breed.",
    "Dogs have no sense of time.",
    "Humans have kept dogs as pets for over 12,000 years.",
    "The largest breed of dog is the Irish Wolfhound.",
    "The world's smallest dog breed is the Chihuahua.",
    "The St. Bernard is the heaviest dog breed.",
    "Only dogs and humans have prostates.",
    "Dogs do not have an appendix.",
    "Every dog on earth likely descended from a species knows as the Tomarctus - a creature that roamed the earth over 15 million years ago.",
    "The oldest known breed is likely the Saluki, originally trained by Egyptians to help them track game.",
    "In 1957, Laika became the first living being in space via an earth satellite and JFK's terrier, Charlie, fathered 4 puppies with Laika's daughter.",
    "An African wolf dog known as the Basenji is the only dog in the world that cannot bark.",
    "There are 703 breeds of purebred dogs.",
    "Dachshunds were originally bred for fighting badgers.",
    "The world's smartest dogs are thought to be (1) the Border Collie, (2) the Poodle, and (3) the Golden Retriever and the dumbest dog is believed to be the Afghan Hound.",
    "A dog's sense of smell is more than 100,000 times stronger than that of a human.",
    "Dogs need a strong sense of smell because their eyesight is not as keen as a human's.",
    "Dogs judge objects first by their movement, then by their brightness, and lastly by their shape.",
    "Chocolate contains a substance known as theobromine (similar to caffeine) which can kill dogs or, at the very least, make them violently ill.",
    "George Washington had 36 dogs - all Foxhounds - with one named Sweetlips.",
    "All dogs are identical in anatomy, with 321 bones and 42 permanent teeth.",
    "Smaller breeds mature faster than larger breeds.",
    "Female dogs are only ready to mate - \"in heat\" - twice a year for a total of roughly 20 days.",
    "Puppies sleep 90% of the day for their first few weeks.",
    "Rin Tin Tin was the first Hollywood dog star and he really signed his movie contracts - all 22 of them - with a paw-print.",
    "Toto in The Wizard of Oz was played by a female Cairn Terrier named Terry.",
    "A dog's vision is not fully developed until after the first month.",
    "Dogs have twice as many muscles to move their ears as people.",
    "The longer a dog's nose, the more effective it's internal cooling system.",
    "An elderly woman was saved by her 12-pound Yorkshire Terrier, who fought off an 80-pound Akita, and survived with only 9 stitches.",
    "U.S. Customs dogs \"Rocky\" and \"Barco\" were so good at patrolling the border that Mexican drug lords put a $300,000 bounty on their heads.",
    "Dogs are all direct descendants of wolves.",
    "Wolves and dogs can mate to produce fertile offspring.",
    "Female wolves have been known to travel great distances to regurgitate full meals for their hungry pups.",
    "Cerberus was the tri-headed dog that guarded the underworld in Greek mythology.",
    "A dog's pregnancy lasts for approximately 60 days.",
    "Dogs' sense of hearing is more than ten times more acute than a human's.",
    "Humans can detect sounds at 20,000 times per second, while dogs can sense frequencies of 30,000 times per second.",
    "The earliest dog fossil dates back to nearly 10,000 B.C.",
    "Bloodhounds are prized for their ability to single out and identify a number of scents simultaneously.",
    "Dalmatian puppies are born completely white.",
    "The ancient Chinese carried Pekingese puppies in the sleeves of their robes.",
    "Boxers are so named because of their manner of playing using their front paws.",
    "All breeds of dog have been found to attack livestock, from 3-month-old puppies to 13-year-old poodles.",
    "A dog's heart beats up to 120 times per minute, or 50% faster than the average human heartbeat of 80 times per minute",
    "The oldest dog on record - a Queensland Heeler named Bluey - was 29 years,5 months old.",
    "Davy Crockett had a dog named Sport.",
    "Dogs were first domesticated by cavemen.",
    "Dogs live an average of 15 years.",
    "Many foot disorders in dogs are simply an issue of too-long toenails.",
    "More than 5,000,000 puppies are born in the U.S. every year.",
    "More than 1 in 3 American families own a dog.",
    "Average body temperature for a dog is 101.2 degrees.",
    "The Girl Scouts and Boy Scouts both offer merit badges in dog care.",
    "Dogs are natural pack animals.",
    "Dogs are naturally submissive to any creature with higher pack status, human or canine.",
    "Puppies' eyes do not fully open until they're about 12 days old.",
    "Dogs with little human contact in the first three months typically don't make good pets.",
    "The Chihuahua was named after the state in Mexico where they were discovered.",
    "The smallest known adult dog was a Yorkshire Terrier that was only 2.5 inches at the shoulder, and weighed only 4 ounces.",
    "The largest dog was an English Mastiff who weighed 343 pounds.",
    "In 2001, it was estimated that there are approximately 400 million dogs in the world.",
    "In Old England, the word \"hound\" was used to refer to all types of dogs.",
    "The process of birthing puppies is called \"whelping.\"",
    "The famous nickname, \"man's best friend\" is used in many other languages as well as English.",
    "Dog's don't see in black-and-white, they have 2 color receptors, and can see yellow and blue.",
    "Dog's definitely don't see like hawks. They have very poor eyesight, but can distinguish movement 10-20 times better than humans.",
    "Even with their poor eyesight, dogs can still see better at night than humans do.",
    "Most dogs have 18 or more muscles to tilt, rotate, and move their ears.",
    "While not the best when it comes to sight, dogs have a keen sense of hearing, and can hear sounds at 4 times the distance of humans.",
    "At the age of 4 weeks, most dogs have developed the majority of their vocalizations.",
    "Most dogs are capable of understanding up to 250 words and gestures.",
    "A Border Collie named Chaser has learned the names of 1,022 toys, and can retrieve each by name.",
    "Dogs can count up to five and can perform simple mathematical calculations.",
    "The average dog is as intelligent as a two-year-old child.",
    "It's been demonstrated that dogs can reduce both physical and emotional anxiety.",
    "Dogs have been used since the 1700's for therapy.",
    "Dogs with a flesh colored nose is said to have a \"Dudley Nose.\"",
    "Pugs and other dogs with short muzzles have a peculiar head-type known as \"Brachycephalic.\"",
    "Hound dogs and long-nosed dogs also have a unique name for their head-type: \"Dolichocephalic.\"",
    "Dogs sleep for an average of 10 hours per day.",
    "Dogs engage in rapid-eye-movement when they sleep, and have dreams just like humans do.",
    "The World Canine Organization recognizes 339 breeds of dogs.",
    "Analysis of the dog genome demonstrate only 4 major types of dogs: Old Lineage Dogs, Mastiff-type Dogs, Herding Dogs, and Modern Hunting Dogs.",
    "Unlike cats, dogs are not exclusively carnivores: they can adapt to different foods, and a percentage of their diets can be fruits and vegetables.",
    "The French Bulldog is incapable of reproducing naturally.",
    "In addition to \"formal\" forms of dog training (operant conditioning, reinforcement, or classical conditioning), dogs are able to learn merely from observation.",
    "The Saint Bernard gains its name from the \"Great St. Bernard Hospice\", the monastery where Barry and other mountain dogs was raised by monks to rescue victims from the snowy Alps.",
    "A Great Dane named \"Just Nuisance\" is the only dog to have officially enlisted in the Royal Navy.",
    "When \"Bobbie,\" a Collie/Shepherd mix, was accidentally abandoned on a family vacation, he traveled 2,551 miles over six months to return to his home.",
    "The are 4 constellations named after dogs.",
    "The Golden Retriever, one of the most popular dog breeds, was first bred in Scotland in the mid 1800s.",
    "A couple of presidential dogs were Golden Retrievers: \"Liberty,\" the presidential dog of Gerald Ford, and \"Victory,\" Ronald Reagan's dog.",
    "Flyball, a dog sport consisting of relays, hurdles, and ball retrieving, was developed in the late 60s, and the first tournament was held in 1983. The current world record for a Flyball race is 14.413 seconds, set by the team \"Touch N Go\" of Las Vegas.",
    "The Labrador Retriever has been the most popular dog breed since 1991.",
    "The Labrador is so popular, in 2006 there were approximately 3-5 times more Labs as there were German Shepherds or Golden Retrievers.",
    "One of the most famous Labrador Retrievers was \"Endal,\" an assistance dog recognized as the most decorated dog in the world. Endal was the first dog to ride on the London Eye (the characteristic ferris wheel in London, England), and was also the first known dog to successfully use a ATM machine.",
    "Two Labradors, Lucky and Flo, were the first dogs known for sniffing out pirated DVDs.",
    "Search and Rescue dog training begins as games played while puppies.",
    "Some Search and Rescue (SaR) Dogs are trained to sniff out humans 1/4 mile away or more.",
    "Some dogs have shown remarkable ability to detect certain cancers.",
    "A dog's powerful sense of smell is frequently called upon to detect anything from mines and explosives to termites and bed bugs.",
    "Conservationists have used dogs to find bumblebee hives in order to protect endangered species.",
    "Puppies love games such as hide and seek! Hide, then call your pup's name so she can try to find you.",
    "Dogs can learn more than 1000 words.",
    "Big happy \"helicopter\" tail wagging is one sign of a really nice dog",
    "Upright, stiff, rapid tail movement is not wagging or \"friendly\" but indicates a dog who's rather excited and focused.",
    "Puppies grow to half their body weight in the first four to five months!",
    "Puppies then take a year or more to gain the other half of their body weight.",
    "Puppies can sleep 18 to 20 hours a day during that rapid body growth phase.",
    "Dogs sometimes appear to smile -- much like humans -- with open mouth grinning. This may indicate a relaxed, submissive state.",
    "Tired puppies get cranky just like little kids. If you have a fussy puppy, try nap time.",
    "The fastest breed, the Greyhound, can run up to 44 miles per hour.",
    "Perky-eared dogs hear sounds better than floppy-eared dogs.",
    "There are about 400 million dogs in the world.",
    "The Labrador Retriever is the most popular breed, according to the American Kennel Club.",
    "There are hundreds of breeds of dogs.",
    "The average dog lives 10 to 14 years.",
    "In general, smaller breeds live longer than larger breeds.",
    "The world's oldest breed, the Saluki, originated in Egypt around 329 B.C.",
    "According to a study shared by Cornell University, dogs were domesticated between 9,000 and 34,000 years ago.",
    "Thomas Jefferson helped enact a dog tax in Virginia, because he was annoyed that dogs were killing his sheep.",
    "Stroking dogs and gazing into their eyes releases the \"feel good\" hormone oxytocin for both people and dogs.",
    "Dogs are omnivores -- they eat meat, grains and vegetables.",
    "The heaviest breed, the Mastiff, weighs about 200 pounds.",
    "More than half of all U.S. presidents have owned dogs.",
    "President Calvin Coolidge owned at least a dozen dogs.",
    "Just like human fingerprints, no two dogs' nose prints are alike.",
    "At about 6 inches, the Chihuahua is the shortest breed.",
    "Irish Wolfhounds, the tallest breed, are 30 to 35 inches tall.",
    "A Russian dog named Laika was the first animal in space, traveling around Earth in 1957.",
    "Dogs who bark the most: Miniature Schnauzers, Cairn Terriers, Yorkshire Terriers, Fox Terriers and West Highland White Terriers.",
    "Puppies have 28 teeth and adult dogs have 42.",
    "The best age to bring a puppy home is 8 to 12 weeks.",
    "Dogs can see best at dawn and dusk.",
    "Dogs aren't colorblind but their eyes don't have receptors for red. They see in shades of black and white and also in shades of blue and yellow.",
    "New puppies have heat sensors in their noses to help find their moms while their eyes and ears are closed.",
    "A dog's sense of smell is reduced by up to 40 percent when he's overheated and panting.",
    "Highly trainable dog breeds like Golden Retrievers, Labrador Retrievers, German Shepherds and Collies are more kid-friendly than some other breeds.",
    "Bichons, Portuguese Water Dogs, Kerry Blue Terriers, Maltese and Poodles are all good choices if you have allergies since they shed less than other breeds.",
    "More than one in three U.S. families owns a dog.",
    "The average number of puppies in a litter is four to six.",
    "There are nearly 14,000 animal shelters and rescue groups across North America.",
    "Service dogs are recognized in the U.S. as \"necessary medical equipment.\"",
    "Therapy dogs, who bring healing to individuals and families by visiting hospitals schools or retirement homes, differ from service dogs, who assist individuals who have disabilities.",
    "The Newfoundland has a water-resistant coat and webbed feet.",
    "As Disney's Cruella De Vil was aware, Dalmatian puppies are born pure white and develop spots as they grow older.",
    "Dogs sweat through the pads of their feet.",
    "Dogs have three eyelids, including one to keep their eyes moist and protected.",
    "Chow Chows are born with pink tongues, which turn blue-black at 8 to 10 weeks.",
    "Dogs are pack animals -- they don't enjoy being alone.",
    "In ancient China, people kept warm by putting dogs up their sleeves.",
    "Dogs who have been spayed or neutered live longer than intact dogs.",
    "A bloodhound named Tigger holds the record for the longest ears, each measuring more than 13 inches.",
    "Bingo is the name of the dog on the box of Cracker Jacks.",
    "In 1969, Lassie was the first animal inducted into the Animal Hall of Fame.",
    "The Alaskan Malamute can withstand temperatures as low as 70 degrees below zero.",
    "Petting a dog can lower your blood pressure.",
    "Stray dogs in Moscow have learned to ride the subway to find food.",
    "Over half of dog owners include their dogs in annual holiday photos.",
    "Although it was once illegal to keep dogs as pets in Iceland's capital city, the laws have been relaxed.",
    "President Lyndon Johnson's beagles were named Him and Her.",
    "One unspayed female dog, her mate and their puppies can produce 67,000 puppies in six years.",
    "The Basenji is the only barkless dog.",
    "Dogs are direct descendants of wolves.",
    "Puppies are blind, deaf and toothless when born.",
    "Dogs curl up to keep themselves warm and protect vital organs.",
    "A dog's sense of smell is 10,000 times stronger than a human's.",
    "The Norwegian Lundehund is the only dog with six toes on each foot.",
    "Dogs can get jealous when their humans display affection toward someone or something else.",
    "Dogs can be trained to detect cancer and other diseases in humans.",
    "A dog's whiskers are used as sensing devices.",
    "Three of the 12 dogs on the Titanic survived.",
    "Your pup reaches his full size between 12 and 24 months.",
    "The U.S. has the highest dog population in the world.",
    "Rin Tin Tin was the first Hollywood dog star.",
    "A dog's average body temperature is 101.2 degrees.",
    "Many foot disorders in dogs are caused by long toenails.",
    "The Boy Scouts and Girl Scouts both offer merit badges in dog care.",
    "The Berger Picard, Miniature American Shepherd and Lagotto Romagnolo are the newest dog breeds recognized by the American Kennel Club in 2015.",
    "Max, Jake, Maggie and Molly are the most popular dog names.",
    "Spiked dog collars were used to protect dogs' throats from wolf attacks in ancient Greece.",
    "Walt Disney's family dog -- named Sunnee -- was the inspiration behind \"Lady and the Tramp.\"",
    "Teams of dogs compete for the fastest time without errors in Flyball races.",
    "A German Shepherd named Orient accompanied her blind owner Bill Irwin as he became the first blind person to through-hike the 2,100-mile Appalachian Trail in 1990.",
    "Chihuahuas are born with soft spots in their skulls, just like human babies.",
    "Mastiffs wore armor and were sent after mounted knights in Roman times.",
    "National Geographic's Dr. Brady Barr measured a dog's average bite force at 320 pounds of pressure per square inch.",
    "Dogs are mentioned in the Bible more than 35 times.",
    "Obesity is the top health problem among dogs.",
    "Dachshunds were originally bred to fight badgers.",
    "President Theodore Roosevelt's Bull Terrier Pete ripped the pants off French Ambassador Jules Jusserand.",
    "The Border Collie, Poodle and Golden Retriever are considered the world's smartest dog breeds.",
    "Smaller breeds of dogs mature faster than larger breeds.",
    "Dogs have twice as many muscles to move their ears as humans, if you're looking for unusual facts about dogs!",
    "Female dogs carry puppies for about nine weeks before birth.",
    "Dogs are naturally submissive to any creature with a higher pack status.",
    "The Chihuahua was named for the state in northwestern Mexico where they were discovered.",
    "Dogs can be taught to count and solve simple math problems.",
    "With love and a little patience, dogs can learn to walk backwards, salute and bow.",
    "Pit bulls have been given a bad rap. BADRAP was started in the San Francisco Bay area on behalf of \"pit bulls and their people\" and was ranked nationally as a No. 1 high-impact nonprofit for animal welfare.",
    "Revolutionary War soldiers sometimes brought their dogs with them into battle. Such was the case with George Washington and his dog, Sweetlips.",
    "The American Water Spaniel was the first hunting breed developed to retrieve from boats.",
    "Dogs have a ligament in the neck which allows them to conserve energy while running long distances following scent trails with their nose to the ground. Many other species have a similar ligament and it is called a Paddywhack.",
    "Dogs evolved from an extinct wolf-like creature in Eurasia 40,000 years ago.",
    "Some studies believe that dogs started to be domesticated 33,000 years ago.",
    "Dogs belong to a biological family called the Canidae, a member of this family is called a canid. This is the origin of the adjective \"canine\" which means \"of or like a dog, relating to or characteristic of dogs\".",
    "Dogs have a very good sense of smell. The part of a dog's brain that analyses smell is 40 times larger than a human's and they can smell 1,000 to 10,000 times better than us.",
    "About one-third of a dog's brain is dedicated to smell.",
    "The breed of dog with the best sense of smell is the bloodhound.",
    "Dog noses are also very cute and easy to boop.",
    "A dog could detect a teaspoon of sugar if you added it to an Olympic-sized swimming pool full of water.",
    "Dogs can be trained to detect cancer in humans.",
    "Some dogs can tell if a human is about to have an epileptic fit.",
    "About 12 percent of the air that a dog breathes goes into a special area in the back of the nose that is dedicated to smelling.",
    "A dog can both sniff and breathe at the same time.",
    "Dogs know from which nostril a smell has entered.",
    "Dogs can use their sense of smell to gauge our emotions, they can smell fear, anxiety, even sadness. This is because they can smell hormones such as adrenaline.",
    "Police dogs can smell human bodies even when they are buried up to 3 meters in the ground.",
    "Dogs see in colors of various shades of blue and yellow.",
    "If you want a dog to see things in a green background the best color is blue.",
    "Humans generally see better than dogs, but dogs see much better when there is low-light.",
    "Dogs cannot distinguish between red and green as these colors would appear as shades of grey to a dog.",
    "Dogs like to chew bones but cooked bones and bones that can splinter such as cooked chicken bones should not be given to dogs.",
    "When dogs were evolving, bone marrow could sometimes form an important part of their diet.",
    "Dogs often bury bones so that they can dig them up at some moment in the future when they are hungry.",
    "Chocolate is poisonous to dogs because it contains theobromine.",
    "Although dogs have some sweat glands in their feet, their principal way of losing heat when they are too hot is by panting.",
    "When dogs have been doing a lot of exercise, they pant. It is not because they are out of breath like a human would be. Dogs have developed the method of losing heat by panting because sweating would not be very efficient due to all the fur.",
    "The normal body temperature of a dog is 100.94 degrees Fahrenheit (38.3 Celsius) to 102.56 F (39.2 C) whereas human normal body temperature 98.6 F (37 C).",
    "Female dogs can get pregnant when their bodies undergo changes which make them receptive to male dogs. This is called being on heat or in estrus.",
    "Male dogs know the female is in heat due to a smell emitted from the female dog.",
    "Most dogs go in heat every 6 months and estrus lasts between 7 and 18 days.",
    "When dogs copulate, it is very normal for them to get stuck together and it may last for up to 45 minutes.",
    "Most vets recommend that female dogs don't get pregnant until the third estrus.",
    "Pregnancy can be prevented by spaying the female dog, this involves removing both the ovaries and the uterus.",
    "Dogs don't go into menopause and will continue to go on heat indefinitely unless they are spayed.",
    "Male dogs have a bone in their penis.",
    "Wolves and dogs can mate to produce fertile offspring.",
    "Dogs normally have between one to sixteen or even more puppies.",
    "It is not possible to know how many puppies a dog will have just by looking. The appearance can be very deceptive.",
    "Puppies are born deaf and cannot hear until they are about 21 days old. The young are born small, blind and helpless and require a long period of parental care.",
    "Most dogs have 42 teeth.",
    "Corgi is Welsh for \"dwarf dog\".",
    "Greyhounds can reach a speed of up to 45 miles per hour.",
    "The most popular breed of domestic dog in the US and the UK is the Labrador Retriever.",
    "The border collie or sheep dog is often considered to be the most intelligent breed of dog some of them have been trained to recognize the words for up to 1,000 objects and retrieved them by verbal command.",
    "Dogs can discriminate the emotional expressions of human faces.",
    "The largest breed of dog is the Irish Wolfhound.",
    "Dogs do not have an appendix. Why haven't humans gotten rid of theirs yet?",
    "Dogs are all direct descendants of wolves.",
    "A dog's heart beats up to 120 times per minute, or 50% faster than the average human heartbeat of 80 times per minute."
];

displayMode();